custom:
  - "https://patreon.com/StatikFinTech_LLC?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink"
  - "https://ko-fi.com/statikfintech_llc"
  - "https://cash.app/$statikmoney8"
  - "https://paypal.me/statikmoney8"
  - "https://www.blockchain.com/btc/address/bc1qarsr966ulmcs3mlcvae7p63v4j2y2vqrw74jl8"
  - "https://etherscan.io/address/0xC2db50A0fc6c95f36Af7171D8C41F6998184103F"
