# Statik-Server Headscale Configuration
# Self-hosted mesh VPN for Mobile-Mirror access

server_url: http://127.0.0.1:8080
listen_addr: 127.0.0.1:8080
metrics_listen_addr: 127.0.0.1:9090

grpc_listen_addr: 127.0.0.1:50443
grpc_allow_insecure: true

private_key_path: .statik/keys/private.key
noise:
  private_key_path: .statik/keys/noise_private.key

# Database
database:
  type: sqlite
  sqlite:
    path: .statik/data/headscale.db

# Prefixes for the tun interface
ip_prefixes:
  - fd7a:115c:a1e0::/48
  - 100.64.0.0/10

# DERP configuration
derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  auto_update_enabled: true
  update_frequency: 24h

# Disable magic DNS to avoid conflicts
magic_dns: false
base_domain: statik.local

# DNS configuration  
dns:
  override_local_dns: false
  nameservers.global:
    - 1.1.1.1
    - 8.8.8.8
  domains: []

# Unix socket for API access
unix_socket: .statik/data/headscale.sock
unix_socket_permission: "0770"

# Logging
log:
  format: text
  level: info

# Policy configuration
policy:
  mode: file
  path: .statik/config/acl.hujson

# Preauth keys configuration  
preauth_key_expiry: 0s  # Never expire
ephemeral_node_inactivity_timeout: 30m

# TLS configuration (disabled for internal use)
tls_cert_path: ""
tls_key_path: ""

# Randomize client port
randomize_client_port: false
